In [0]:
# set whether normal process or being run by Elsevier supporters
permissions = 'fulldata' # default or fulldata
# set the project name
project_name = 'proj_050_teamscience'  # This is the folder name that you work in, e.g. 'test_project_1'

In [0]:
#Alick: I'll switch to the latest snapshot (v008) - wording there is confusing! 
#%run /Snippets/header_latest

In [0]:
%run /Snippets/header_008

## Python Libraries and Functions

In [0]:
# libraries 
from pyspark.sql.functions import col, count, explode, array, mean, stddev, filter, percentile_approx, arrays_zip, size, array_distinct, sum, reverse, collect_list, array_sort, posexplode, max, arrays_overlap, lit, when, cast
from pyspark.ml.feature import VectorAssembler
from pyspark.ml.regression import LinearRegression
import pandas as pd
import matplotlib.pyplot as plt
from pyspark.sql import Window
from pyspark.ml.feature import StringIndexer

# make a DF to store everything
model_output_df = pd.DataFrame(columns = ["model", "coef", "se", "t", "p", "r2"])
descriptives_output_df = pd.DataFrame(columns = ["model", "subjareas", "mean", "sd", "sample", "median", "iqr_25", "iqr_75"])

# model summary print out 
def modelsummary(model, hyp_model, df):
    import numpy as np
    print ("Note: the last rows are the information for Intercept")
    print ("##","-------------------------------------------------")
    print ("##","  Estimate   |   Std.Error | t Values  |  P-value")
    coef = np.append(list(model.coefficients),model.intercept)
    Summary=model.summary

    for i in range(len(Summary.pValues)):
        print ("##",'{:10.6f}'.format(coef[i]),\
        '{:10.6f}'.format(Summary.coefficientStandardErrors[i]),\
        '{:8.3f}'.format(Summary.tValues[i]),\
        '{:10.6f}'.format(Summary.pValues[i]))
        # store the data 
        row = pd.DataFrame({"model": hyp_model, "coef": coef[i], "se": Summary.coefficientStandardErrors[i], 
               "t": Summary.tValues[i], "p": Summary.pValues[i], "r2": Summary.r2}, index = [0])
        df = pd.concat([df, row], ignore_index = True, axis = 0)

    print ("##",'---')
    print ("##","Mean squared error: % .6f" \
           % Summary.meanSquaredError, ", RMSE: % .6f" \
           % Summary.rootMeanSquaredError )
    print ("##","Multiple R-squared: %f" % Summary.r2, ", \
            Total iterations: %i"% Summary.totalIterations)
    return(df)

## Research Question 1a

### Descriptive Statistics

We will first calculate the mean, median, and interquartile range of team size by discipline. We will not explicitly compare discipline intercepts in a post hoc format with any form of test. Instead we will use visualization techniques to display the distribution and their interquartile range for readers to examine (i.e., a forest plot).

In [0]:
# load the ANI dataframe which contains author information 
df_ani = spark.read.format("parquet").load(basePath+tablename_ani)
df_ani.createOrReplaceTempView("df_ani")
df_ani.printSchema()
df_ani_smaller = df_ani.filter(df_ani.Year > 1969)\
  .filter(df_ani.publication_type == "ar")\
  .sample(False, .25, 8675309) 

df_ani_smaller.count()

# display(df_ani)

root
 |-- Eid: long (nullable = true)
 |-- Year: integer (nullable = true)
 |-- title: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- title: string (nullable = true)
 |    |    |-- lang: string (nullable = true)
 |    |    |-- original: string (nullable = true)
 |-- ASJC: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- subjareas: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- Af: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- affiliation_address_part: string (nullable = true)
 |    |    |-- affiliation_city: string (nullable = true)
 |    |    |-- affiliation_city_group: string (nullable = true)
 |    |    |-- affiliation_country: string (nullable = true)
 |    |    |-- affiliation_ids: array (nullable = true)
 |    |    |    |-- element: long (containsNull = true)
 |    |    |-- affiliation_organization: array (nullable = true)
 |    |    |    |-- element: string (containsNull = true)
 |    |    |-- affiliation_organization_count: short (nullable = true)
 |    |    |-- affiliation_postal_code: string (nullable = true)
 |    |    |-- affiliation_state: string (nullable = true)
 |    |    |-- affiliation_tag_country: string (nullable = true)
 |    |    |-- affiliation_text: string (nullable = true)
 |    |    |-- afid: long (nullable = true)
 |    |    |-- dptid: long (nullable = true)
 |-- Au: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- Authorseq: integer (nullable = true)
 |    |    |-- auid: long (nullable = true)
 |    |    |-- author_type: string (nullable = true)
 |    |    |-- collaboration: string (nullable = true)
 |    |    |-- degrees: string (nullable = true)
 |    |    |-- email_sha1: string (nullable = true)
 |    |    |-- given_name: string (nullable = true)
 |    |    |-- given_name_pn: string (nullable = true)
 |    |    |-- indexed_name: string (nullable = true)
 |    |    |-- indexed_name_pn: string (nullable = true)
 |    |    |-- initials: string (nullable = true)
 |    |    |-- initials_pn: string (nullable = true)
 |    |    |-- nametext: string (nullable = true)
 |    |    |-- orcid: string (nullable = true)
 |    |    |-- suffix: string (nullable = true)
 |    |    |-- surname: string (nullable = true)
 |    |    |-- surname_pn: string (nullable = true)
 |-- Au_Af: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- Authorseq: short (nullable = true)
 |    |    |-- affiliation_seq: short (nullable = true)
 |    |    |-- validity_B: boolean (nullable = true)
 |-- Au_cors: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- Authorseq: integer (nullable = true)
 |    |    |-- auid: long (nullable = true)
 |    |    |-- author_type: string (nullable = true)
 |    |    |-- collaboration: string (nullable = true)
 |    |    |-- degrees: string (nullable = true)
 |    |    |-- email_sha1: string (nullable = true)
 |    |    |-- given_name: string (nullable = true)
 |    |    |-- given_name_pn: string (nullable = true)
 |    |    |-- indexed_name: string (nullable = true)
 |    |    |-- indexed_name_pn: string (nullable = true)
 |    |    |-- initials: string (nullable = true)
 |    |    |-- initials_pn: string (nullable = true)
 |    |    |-- nametext: string (nullable = true)
 |    |    |-- orcid: string (nullable = true)
 |    |    |-- suffix: string (nullable = true)
 |    |    |-- surname: string (nullable = true)
 |    |    |-- surname_pn: string (nullable = true)
 |-- abstract: string (nullable = true)
 |-- abstract_lang: string (nullable = true)
 |-- publication_type: string (nullable = true)
 |-- references: array (nullable = true)
 |    |-- element: long (containsNull = true)
 |-- copyright_types: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- sort_yyyymm: string (nullable = true)
 |-- openaccess: string (nullable = true)
 |-- pmid: string (nullable = true)
 |-- doi: string (nullable = true)
 |-- n_references: long (nullable = true)
 |-- correspondence: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- country: string (nullable = true)
 |    |    |-- txt: string (nullable = true)
 |-- orig_load_date: string (nullable = true)
 |-- date_sort_day: string (nullable = true)
 |-- date_sort_month: string (nullable = true)
 |-- datesort: string (nullable = true)
 |-- issn: string (nullable = true)
 |-- issue: string (nullable = true)
 |-- volume: string (nullable = true)
 |-- firstpage: string (nullable = true)
 |-- lastpage: string (nullable = true)
 |-- meta_language: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- meta_source_country: string (nullable = true)
 |-- keywords: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- source: struct (nullable = true)
 |    |-- article_number: string (nullable = true)
 |    |-- conferenceinfo: struct (nullable = true)
 |    |    |-- enddate: string (nullable = true)
 |    |    |-- location: string (nullable = true)
 |    |    |-- name: string (nullable = true)
 |    |    |-- startdate: string (nullable = true)
 |    |-- country: string (nullable = true)
 |    |-- date_day: string (nullable = true)
 |    |-- date_month: string (nullable = true)
 |    |-- date_text: string (nullable = true)
 |    |-- date_year: string (nullable = true)
 |    |-- e_address: string (nullable = true)
 |    |-- e_address_type: string (nullable = true)
 |    |-- isbn_electronic: array (nullable = true)
 |    |    |-- element: string (containsNull = true)
 |    |-- isbn_other: array (nullable = true)
 |    |    |-- element: string (containsNull = true)
 |    |-- isbn_print: array (nullable = true)
 |    |    |-- element: string (containsNull = true)
 |    |-- issn_electronic: array (nullable = true)
 |    |    |-- element: string (containsNull = true)
 |    |-- issn_other: array (nullable = true)
 |    |    |-- element: string (containsNull = true)
 |    |-- issn_print: array (nullable = true)
 |    |    |-- element: string (containsNull = true)
 |    |-- publishername: string (nullable = true)
 |    |-- sourcetitle: string (nullable = true)
 |    |-- sourcetitle_abbrev: string (nullable = true)
 |    |-- srcid: long (nullable = true)
 |    |-- type: string (nullable = true)
 |    |-- website: string (nullable = true)
 |-- dbcollections: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- free_to_read_status_list: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- funding_list: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- agency: string (nullable = true)
 |    |    |-- agency_acronym: string (nullable = true)
 |    |    |-- agency_country: string (nullable = true)
 |    |    |-- agency_id: string (nullable = true)
 |    |    |-- agency_matched_string: string (nullable = true)
 |    |    |-- ids: array (nullable = true)
 |    |    |    |-- element: string (containsNull = true)
 |-- CitationCount: long (nullable = true)

Out[10]: 14854906

In [0]:
df_hyp1 = df_ani_smaller.select("Eid", "Year", "Au", "ASJC", "CitationCount")\
  .withColumn("Au", explode("Au"))\
  .withColumn("ASJC", explode("ASJC"))

df_hyp1 = df_hyp1\
  .withColumn('subjareas',
              when(df_hyp1.ASJC.between(1100, 1199), "Life Sciences")\
  .when(df_hyp1.ASJC.between(1200, 1299), "Social Sciences")\
  .when(df_hyp1.ASJC.between(1300, 1399), "Life Sciences")\
  .when(df_hyp1.ASJC.between(1400, 1499), "Social Sciences")\
  .when(df_hyp1.ASJC.between(1500, 1799), "Physical Sciences")\
  .when(df_hyp1.ASJC.between(1800, 1899), "Social Sciences")\
  .when(df_hyp1.ASJC.between(1900, 1999), "Physical Sciences")\
  .when(df_hyp1.ASJC.between(2000, 2099), "Social Sciences")\
  .when(df_hyp1.ASJC.between(2100, 2399), "Physical Sciences")\
  .when(df_hyp1.ASJC.between(2400, 2499), "Life Sciences")\
  .when(df_hyp1.ASJC.between(2500, 2699), "Physical Sciences")\
  .when(df_hyp1.ASJC.between(2700, 2799), "Health Sciences")\
  .when(df_hyp1.ASJC.between(2800, 2899), "Life Sciences")\
  .when(df_hyp1.ASJC.between(2900, 2999), "Health Sciences")\
  .when(df_hyp1.ASJC.between(3000, 3099), "Life Sciences")\
  .when(df_hyp1.ASJC.between(3100, 3199), "Physical Sciences")\
  .when(df_hyp1.ASJC.between(3200, 3399), "Social Sciences")\
  .when(df_hyp1.ASJC.between(3400, 3699), "Health Sciences")\
  .otherwise("Multidisciplinary")
  ).groupBy("Eid", "Year", "subjareas", "CitationCount")\
  .agg(count("Au").alias("team_size"))

In [0]:
summary_df = df_hyp1.select("subjareas", "team_size")\
  .groupBy("subjareas")\
  .agg(mean("team_size").alias("mean"), stddev("team_size").alias("sd"), count("team_size").alias("sample"), percentile_approx("team_size", 0.5, 10000).alias("median"), percentile_approx("team_size", 0.25, 10000).alias("iqr_25"), percentile_approx("team_size", 0.75, 10000).alias("iqr_75"))\
  .toPandas()
summary_df["model"] = "hyp1a"
descriptives_output_df = pd.concat([descriptives_output_df, summary_df], ignore_index = True, axis = 0)

# descriptives_output_df

### Overall Summary

In order to determine if team sizes change overall across time, we will use a linear model of team size predicted by year of publication in which each article is only represented once, regardless of discipline. We will examine if the confidence interval of the slope parameter is different from zero to determine if the predictor was significant.

In [0]:
# 4.19s on default #54.96 seconds on fulldata 
# get the total number of authors by year 
df_hyp1_overall = df_ani_smaller.select("Eid", "Year", "Au", "CitationCount", explode("Au").alias("author"))\
  .groupBy("Eid", "Year", "CitationCount")\
  .agg(count("author").alias("team_size"))

# display(df_hyp1_overall)

# team size ~ year of publication on the entire dataset 
# the "features" or X must be in this feature format
vectorAssembler = VectorAssembler(inputCols = ['Year'], outputCol = "pub_year")
df_hyp1_overall = vectorAssembler.setHandleInvalid("skip").transform(df_hyp1_overall)

# put in the features X and prediction Y
lr = LinearRegression(featuresCol = 'pub_year', labelCol='team_size')
lr_model = lr.fit(df_hyp1_overall)
model_output_df = modelsummary(lr_model, "hyp1a", model_output_df)

# model_output_df

Note: the last rows are the information for Intercept
## -------------------------------------------------
##   Estimate   |   Std.Error | t Values  |  P-value
##   0.075928   0.000321  236.450   0.000000
## -148.041472   0.643774 -229.959   0.000000
## ---
## Mean squared error:  315.727625 , RMSE:  17.768726
## Multiple R-squared: 0.003825 ,             Total iterations: 0

### Summary By Subject Area

Last, we will calculate each discipline's slope and confidence interval using a linear model of team size predicted by year of publication. Again, we will provide these slopes in a visualization for readers to examine with no official post hoc comparison. While a multilevel model would allow us to embed all disciplines within one model, no *pyspark* multilevel model implementation exists to model data at this scale.

In [0]:


for AREA in descriptives_output_df.subjareas.unique():
  if AREA == 'undefined': continue
  print(AREA)
  print("\n-------\n")
  temp_df = df_hyp1.select("subjareas", "team_size", "Year")\
    .filter(df_hyp1.subjareas == AREA)
  
  vectorAssembler = VectorAssembler(inputCols = ['Year'], outputCol = "pub_year")
  temp_df = vectorAssembler.setHandleInvalid("skip").transform(temp_df)
  lr = LinearRegression(featuresCol = 'pub_year', labelCol='team_size')
  lr_model = lr.fit(temp_df)
  model_output_df = modelsummary(lr_model, ("hyp1a_"+AREA), model_output_df)
  
# model_output_df

Health Sciences

-------

Note: the last rows are the information for Intercept
## -------------------------------------------------
##   Estimate   |   Std.Error | t Values  |  P-value
##   0.183990   0.009037   20.361   0.000000
## -359.829970  18.155336  -19.820   0.000000
## ---
## Mean squared error:  285.209701 , RMSE:  16.888153
## Multiple R-squared: 0.010320 ,             Total iterations: 0
Physical Sciences

-------

Note: the last rows are the information for Intercept
## -------------------------------------------------
##   Estimate   |   Std.Error | t Values  |  P-value
##   0.265573   0.026587    9.989   0.000000
## -521.409270  53.454498   -9.754   0.000000
## ---
## Mean squared error:  4114.805612 , RMSE:  64.146751
## Multiple R-squared: 0.001462 ,             Total iterations: 0
Multidisciplinary

-------

Note: the last rows are the information for Intercept
## -------------------------------------------------
##   Estimate   |   Std.Error | t Values  |  P-value
##   0.113620   0.056635    2.006   0.044885
## -219.613206 113.770369   -1.930   0.053619
## ---
## Mean squared error:  1798.629262 , RMSE:  42.410249
## Multiple R-squared: 0.000731 ,             Total iterations: 0
Social Sciences

-------

Note: the last rows are the information for Intercept
## -------------------------------------------------
##   Estimate   |   Std.Error | t Values  |  P-value
##   0.060509   0.005188   11.663   0.000000
## -116.552976  10.425110  -11.180   0.000000
## ---
## Mean squared error:  44.172875 , RMSE:  6.646268
## Multiple R-squared: 0.008043 ,             Total iterations: 0
Life Sciences

-------

Note: the last rows are the information for Intercept
## -------------------------------------------------
##   Estimate   |   Std.Error | t Values  |  P-value
##   0.196390   0.005978   32.851   0.000000
## -383.853702  12.011396  -31.957   0.000000
## ---
## Mean squared error:  152.368723 , RMSE:  12.343773
## Multiple R-squared: 0.021575 ,             Total iterations: 0

## Research Question 1b

### Descriptive Statistics

For this research question, we will examine the impact of team size on article publication metrics for impact. Our hypothesis is that team size impacts article metrics (non-directional). We will run these analyses once for each dependent variable of citation count and weighted citation five year count. We will calculate the mean, median, and interquartile range of each publication metric by discipline. We will visualize these values instead of comparing them directly.

In [0]:
# grab Citations_5y from df_fwci
df_fwci = spark.read.format("parquet").load(fwci_parquet_path)
df_fwci.createOrReplaceTempView("df_fwci")

# display(df_fwci)

# merge this information with tables from above 
df_hyp1_overall = df_hyp1_overall.join(df_fwci.select("Eid", "Citations_5y"), "Eid", "left")

df_hyp1 = df_hyp1.join(df_fwci.select("Eid", "Citations_5y"), "Eid", "left")

In [0]:
# summarize citation count
summary_df = df_hyp1.select("subjareas", "CitationCount")\
  .groupBy("subjareas")\
  .agg(mean("CitationCount").alias("mean"), 
       stddev("CitationCount").alias("sd"), 
       count("CitationCount").alias("sample"), 
       percentile_approx("CitationCount", 0.5, 10000).alias("median"),
       percentile_approx("CitationCount", 0.25, 10000).alias("iqr_25"), 
       percentile_approx("CitationCount", 0.75, 10000).alias("iqr_75"))\
  .toPandas()
summary_df["model"] = "hyp1b_CitationCount"
descriptives_output_df = pd.concat([descriptives_output_df, summary_df], ignore_index = True, axis = 0)

# summarize citation 5y, exclude last 5 years in graph
summary_df = df_hyp1.select("subjareas", "Citations_5y")\
  .groupBy("subjareas")\
  .agg(mean("Citations_5y").alias("mean"), 
       stddev("Citations_5y").alias("sd"), 
       count("Citations_5y").alias("sample"), 
       percentile_approx("Citations_5y", 0.5, 10000).alias("median"),
       percentile_approx("Citations_5y", 0.25, 10000).alias("iqr_25"), 
       percentile_approx("Citations_5y", 0.75, 10000).alias("iqr_75"))\
  .toPandas()
summary_df["model"] = "hyp1b_Citation5y"
descriptives_output_df = pd.concat([descriptives_output_df, summary_df], ignore_index = True, axis = 0)

### Overall Summary 
To determine the impact of team size on publication metrics, we will use a linear model of publication metrics predicted by time (covariate) and team size. We will include time as a covariate, as we expect that older articles will potentially have more or different metrics because they have been around longer to cite. We will examine if the confidence interval of the team size slope parameter is different from zero.

In [0]:
# citation count ~ year of publication + team_size
# the "features" or X must be in this feature format
df_hyp1_overall = df_hyp1_overall.drop("pub_year")
vectorAssembler = VectorAssembler(inputCols = ['Year', 'team_size'], outputCol = "pub_year")
df_hyp1_overall = vectorAssembler.setHandleInvalid("skip").transform(df_hyp1_overall)

# put in the features X and prediction Y
lr = LinearRegression(featuresCol = 'pub_year', labelCol = 'CitationCount')
lr_model = lr.fit(df_hyp1_overall)
model_output_df = modelsummary(lr_model, "hyp1b_CitationCount", model_output_df)

# model_output_df

Note: the last rows are the information for Intercept
## -------------------------------------------------
##   Estimate   |   Std.Error | t Values  |  P-value
## -13.922517   0.212294  -65.581   0.000000
##   0.581451   0.061245    9.494   0.000000
## 28122.322635 426.607220   65.921   0.000000
## ---
## Mean squared error:  583112.970305 , RMSE:  763.618341
## Multiple R-squared: 0.029424 ,             Total iterations: 0

In [0]:
# citation_5y ~ year of publication + team_size
# the "features" or X must be in this feature format
df_hyp1_overall_sub = df_hyp1_overall.drop("pub_year")\
  .filter(df_hyp1_overall.Year < 2017).where(col("Citations_5y").isNotNull())
vectorAssembler = VectorAssembler(inputCols = ['Year', 'team_size'], outputCol = "pub_year")
df_hyp1_overall = vectorAssembler.setHandleInvalid("skip").transform(df_hyp1_overall_sub)

# put in the features X and prediction Y
lr = LinearRegression(featuresCol = 'pub_year', labelCol = 'Citations_5y')
lr_model = lr.fit(df_hyp1_overall)
model_output_df = modelsummary(lr_model, "hyp1b_Citation5y", model_output_df)

# model_output_df

Note: the last rows are the information for Intercept
## -------------------------------------------------
##   Estimate   |   Std.Error | t Values  |  P-value
##   0.622689   0.050632   12.298   0.000000
##   0.379534   0.011883   31.939   0.000000
## -1208.284562 101.575004  -11.895   0.000000
## ---
## Mean squared error:  21314.166674 , RMSE:  145.993721
## Multiple R-squared: 0.011203 ,             Total iterations: 0

### Summary By Subject Area
Last, we will calculate the slope for team size for each discipline separately. We will visualize these differences and the confidence intervals.

In [0]:
for AREA in descriptives_output_df.subjareas.unique():
  if AREA == 'undefined': continue
  print(AREA)
  print("\n-------\n")
  temp_df = df_hyp1.select("subjareas", "team_size", "Year", "CitationCount", "Citations_5y")\
    .filter(df_hyp1.subjareas == AREA)
  
  vectorAssembler = VectorAssembler(inputCols = ['Year', 'team_size'], outputCol = "pub_year")
  temp_df = vectorAssembler.setHandleInvalid("skip").transform(temp_df)
  lr = LinearRegression(featuresCol = 'pub_year', labelCol='CitationCount')
  lr_model = lr.fit(temp_df)
  model_output_df = modelsummary(lr_model, ("hyp1b_CitationCount_"+AREA), model_output_df)
  
  lr = LinearRegression(featuresCol = 'pub_year', labelCol='Citations_5y')
  lr_model = lr.fit(temp_df.filter(temp_df.Year < 2017).where(col("Citations_5y").isNotNull()))
  model_output_df = modelsummary(lr_model, ("hyp1b_Citation5y_"+AREA), model_output_df)
  
# model_output_df

Health Sciences

-------

Note: the last rows are the information for Intercept
## -------------------------------------------------
##   Estimate   |   Std.Error | t Values  |  P-value
## -10.314310   0.272629  -37.833   0.000000
##   1.884351   0.150525   12.519   0.000000
## 20832.313046 547.587849   38.044   0.000000
## ---
## Mean squared error:  256910.856621 , RMSE:  506.863746
## Multiple R-squared: 0.036530 ,             Total iterations: 0
Note: the last rows are the information for Intercept
## -------------------------------------------------
##   Estimate   |   Std.Error | t Values  |  P-value
##   0.398839   0.126252    3.159   0.001584
##   1.817312   0.082325   22.075   0.000000
## -773.215033 253.163072   -3.054   0.002258
## ---
## Mean squared error:  36399.360624 , RMSE:  190.786165
## Multiple R-squared: -0.000324 ,             Total iterations: 0
Physical Sciences

-------

Note: the last rows are the information for Intercept
## -------------------------------------------------
##   Estimate   |   Std.Error | t Values  |  P-value
## -13.652960   0.267046  -51.126   0.000000
##   0.266300   0.039509    6.740   0.000000
## 27573.031306 536.902738   51.356   0.000000
## ---
## Mean squared error:  411763.979314 , RMSE:  641.688382
## Multiple R-squared: 0.037249 ,             Total iterations: 0
Note: the last rows are the information for Intercept
## -------------------------------------------------
##   Estimate   |   Std.Error | t Values  |  P-value
##   0.749077   0.063210   11.851   0.000000
##   0.117705   0.006469   18.197   0.000000
## -1467.110279 126.848785  -11.566   0.000000
## ---
## Mean squared error:  14322.482568 , RMSE:  119.676575
## Multiple R-squared: 0.006395 ,             Total iterations: 0
Multidisciplinary

-------

Note: the last rows are the information for Intercept
## -------------------------------------------------
##   Estimate   |   Std.Error | t Values  |  P-value
## -31.399987   1.553231  -20.216   0.000000
##   2.240935   0.396077    5.658   0.000000
## 63449.004658 3120.168463   20.335   0.000000
## ---
## Mean squared error:  1280390.128592 , RMSE:  1131.543251
## Multiple R-squared: 0.073410 ,             Total iterations: 0
Note: the last rows are the information for Intercept
## -------------------------------------------------
##   Estimate   |   Std.Error | t Values  |  P-value
##  -0.754208   0.378716   -1.991   0.046490
##   0.980279   0.075694   12.951   0.000000
## 1629.044461 759.715335    2.144   0.032066
## ---
## Mean squared error:  55938.186600 , RMSE:  236.512551
## Multiple R-squared: 0.037397 ,             Total iterations: 0
Social Sciences

-------

Note: the last rows are the information for Intercept
## -------------------------------------------------
##   Estimate   |   Std.Error | t Values  |  P-value
## -16.952818   0.542665  -31.240   0.000000
##   1.407589   1.152782    1.221   0.222090
## 34219.296985 1089.721142   31.402   0.000000
## ---
## Mean squared error:  459417.546724 , RMSE:  677.803472
## Multiple R-squared: 0.059319 ,             Total iterations: 0
Note: the last rows are the information for Intercept
## -------------------------------------------------
##   Estimate   |   Std.Error | t Values  |  P-value
##   0.372928   0.055210    6.755   0.000000
##   0.639716   0.109348    5.850   0.000000
## -725.263987 110.658989   -6.554   0.000000
## ---
## Mean squared error:  2947.093554 , RMSE:  54.287140
## Multiple R-squared: 0.009139 ,             Total iterations: 0
Life Sciences

-------

Note: the last rows are the information for Intercept
## -------------------------------------------------
##   Estimate   |   Std.Error | t Values  |  P-value
## -12.305345   0.362474  -33.948   0.000000
##   0.712859   0.253261    2.815   0.004884
## 24848.186852 727.928638   34.135   0.000000
## ---
## Mean squared error:  550632.741788 , RMSE:  742.046321
## Multiple R-squared: 0.020095 ,             Total iterations: 0
Note: the last rows are the information for Intercept
## -------------------------------------------------
##   Estimate   |   Std.Error | t Values  |  P-value
##   0.285243   0.085803    3.324   0.000887
##   0.785416   0.064806   12.120   0.000000
## -539.910452 172.029872   -3.138   0.001700
## ---
## Mean squared error:  20102.845851 , RMSE:  141.784505
## Multiple R-squared: -0.002791 ,             Total iterations: 0

# Output Tables

Output tables for writing manuscript in R markdown.

In [0]:
# write out results section until I can get download link
pd.set_option('display.max_rows', None)
model_output_df

,model,coef,se,t,p,r2
0,hyp1a,0.101687,0.009138,11.127818,0.0,0.000861
1,hyp1a,-198.50472,18.363503,-10.809741,0.0,0.000861
2,hyp1a_Health Sciences,0.18399,0.009037,20.360572,0.0,0.01032
3,hyp1a_Health Sciences,-359.82997,18.155336,-19.819516,0.0,0.01032
4,hyp1a_Physical Sciences,0.265573,0.026587,9.988784,0.0,0.001462
5,hyp1a_Physical Sciences,-521.40927,53.454498,-9.754264,0.0,0.001462
6,hyp1a_Multidisciplinary,0.11362,0.056635,2.006186,0.044885,0.000731
7,hyp1a_Multidisciplinary,-219.613206,113.770369,-1.93032,0.053619,0.000731
8,hyp1a_Social Sciences,0.060509,0.005188,11.663092,0.0,0.008043
9,hyp1a_Social Sciences,-116.552976,10.42511,-11.180023,0.0,0.008043
10,hyp1a_Life Sciences,0.19639,0.005978,32.851412,0.0,0.021575
11,hyp1a_Life Sciences,-383.853702,12.011396,-31.957459,0.0,0.021575
12,hyp1b_CitationCount,-13.922517,0.212294,-65.581378,0.0,0.029424
13,hyp1b_CitationCount,0.581451,0.061245,9.493769,0.0,0.029424
14,hyp1b_CitationCount,28122.322635,426.60722,65.920878,0.0,0.029424
15,hyp1b_Citation5y,0.622689,0.050632,12.298438,0.0,0.011203
16,hyp1b_Citation5y,0.379534,0.011883,31.939252,0.0,0.011203
17,hyp1b_Citation5y,-1208.284562,101.575004,-11.895491,0.0,0.011203
18,hyp1b_CitationCount_Health Sciences,-10.31431,0.272629,-37.832819,0.0,0.03653
19,hyp1b_CitationCount_Health Sciences,1.884351,0.150525,12.518552,0.0,0.03653
20,hyp1b_CitationCount_Health Sciences,20832.313046,547.587849,38.043783,0.0,0.03653
21,hyp1b_Citation5y_Health Sciences,0.398839,0.126252,3.159069,0.001584,-0.000324
22,hyp1b_Citation5y_Health Sciences,1.817312,0.082325,22.074911,0.0,-0.000324
23,hyp1b_Citation5y_Health Sciences,-773.215033,253.163072,-3.054217,0.002258,-0.000324
24,hyp1b_CitationCount_Physical Sciences,-13.65296,0.267046,-51.125781,0.0,0.037249
25,hyp1b_CitationCount_Physical Sciences,0.2663,0.039509,6.740163,0.0,0.037249
26,hyp1b_CitationCount_Physical Sciences,27573.031306,536.902738,51.355729,0.0,0.037249
27,hyp1b_Citation5y_Physical Sciences,0.749077,0.06321,11.850593,0.0,0.006395
28,hyp1b_Citation5y_Physical Sciences,0.117705,0.006469,18.196501,0.0,0.006395
29,hyp1b_Citation5y_Physical Sciences,-1467.110279,126.848785,-11.56582,0.0,0.006395
30,hyp1b_CitationCount_Multidisciplinary,-31.399987,1.553231,-20.215914,0.0,0.07341
31,hyp1b_CitationCount_Multidisciplinary,2.240935,0.396077,5.657823,0.0,0.07341
32,hyp1b_CitationCount_Multidisciplinary,63449.004658,3120.168463,20.335121,0.0,0.07341
33,hyp1b_Citation5y_Multidisciplinary,-0.754208,0.378716,-1.991486,0.04649,0.037397
34,hyp1b_Citation5y_Multidisciplinary,0.980279,0.075694,12.950628,0.0,0.037397
35,hyp1b_Citation5y_Multidisciplinary,1629.044461,759.715335,2.144283,0.032066,0.037397
36,hyp1b_CitationCount_Social Sciences,-16.952818,0.542665,-31.239923,0.0,0.059319
37,hyp1b_CitationCount_Social Sciences,1.407589,1.152782,1.221036,0.22209,0.059319
38,hyp1b_CitationCount_Social Sciences,34219.296985,1089.721142,31.401884,0.0,0.059319
39,hyp1b_Citation5y_Social Sciences,0.372928,0.05521,6.754665,0.0,0.009139
40,hyp1b_Citation5y_Social Sciences,0.639716,0.109348,5.850297,0.0,0.009139
41,hyp1b_Citation5y_Social Sciences,-725.263987,110.658989,-6.554045,0.0,0.009139
42,hyp1b_CitationCount_Life Sciences,-12.305345,0.362474,-33.948199,0.0,0.020095
43,hyp1b_CitationCount_Life Sciences,0.712859,0.253261,2.814721,0.004884,0.020095
44,hyp1b_CitationCount_Life Sciences,24848.186852,727.928638,34.135471,0.0,0.020095
45,hyp1b_Citation5y_Life Sciences,0.285243,0.085803,3.324375,0.000887,-0.002791
46,hyp1b_Citation5y_Life Sciences,0.785416,0.064806,12.119503,0.0,-0.002791
47,hyp1b_Citation5y_Life Sciences,-539.910452,172.029872,-3.138469,0.0017,-0.002791
48,hyp2_CitationCount_country_count,-13.686834,0.253045,-54.088443,0.0,0.024435
49,hyp2_CitationCount_country_count,0.262018,0.088854,2.948857,0.003192,0.024435
50,hyp2_CitationCount_country_count,23.950706,2.066882,11.587842,0.0,0.024435
51,hyp2_CitationCount_country_count,27617.694605,508.258055,54.337938,0.0,0.024435
52,hyp2_Citation5y_country_count,0.491549,0.105386,4.664289,0.000003,0.018954
53,hyp2_Citation5y_country_count,-0.004073,0.033737,-0.120734,0.903902,0.018954
54,hyp2_Citation5y_country_count,16.916044,0.907492,18.640439,0.0,0.018954
55,hyp2_Citation5y_country_count,-965.056689,211.288816,-4.567476,0.000005,0.018954
56,hyp2_CitationCount_inst_count,-14.658246,0.358974,-40.833732,0.0,0.037325
57,hyp2_CitationCount_inst_count,-0.326129,0.118528,-2.751505,0.005933,0.037325
58,hyp2_CitationCount_inst_count,8.573047,1.071677,7.999657,0.0,0.037325
59,hyp2_CitationCount_inst_count,29589.802099,721.106332,41.033896,0.0,0.037325
60,hyp2_Citation5y_inst_count,0.395882,0.102929,3.846169,0.00012,0.010505
61,hyp2_Citation5y_inst_count,-0.181945,0.032275,-5.637268,0.0,0.010505
62,hyp2_Citation5y_inst_count,4.587187,0.296101,15.491982,0.0,0.010505
63,hyp2_Citation5y_inst_count,-759.484452,206.424788,-3.679231,0.000234,0.010505
64,hyp2_CitationCount_gender_percent,-13.843451,0.513714,-26.947797,0.0,0.020355
65,hyp2_CitationCount_gender_percent,0.740978,0.172839,4.287105,0.000018,0.020355
66,hyp2_CitationCount_gender_percent,41.397328,18.450247,2.243728,0.024855,0.020355
67,hyp2_CitationCount_gender_percent,27943.012465,1034.839644,27.002263,0.0,0.020355
68,hyp2_Citation5y_gender_percent,0.770525,0.092668,8.31491,0.0,0.009497
69,hyp2_Citation5y_gender_percent,0.29117,0.025858,11.260463,0.0,0.009497
70,hyp2_Citation5y_gender_percent,9.963322,3.109763,3.203885,0.001356,0.009497
71,hyp2_Citation5y_gender_percent,-1507.862326,186.310665,-8.093269,0.0,0.009497
72,hyp2_CitationCount_HIndex,-14.527634,1.13032,-12.852668,0.0,0.019441
73,hyp2_CitationCount_HIndex,1.477282,0.84405,1.75023,0.080097,0.019441
74,hyp2_CitationCount_HIndex,6.839672,0.777035,8.802267,0.0,0.019441
75,hyp2_CitationCount_HIndex,29315.960556,2270.94456,12.909149,0.0,0.019441
76,hyp2_Citation5y_HIndex,0.722212,0.167095,4.322167,0.000016,0.026545
77,hyp2_Citation5y_HIndex,0.172656,0.036876,4.682121,0.000003,0.026545
78,hyp2_Citation5y_HIndex,1.238219,0.108824,11.378203,0.0,0.026545
79,hyp2_Citation5y_HIndex,-1409.884331,335.273627,-4.205175,0.000026,0.026545
80,hyp2_CitationCount_HIndex_noself,-10.775592,0.690742,-15.600017,0.0,0.033309
81,hyp2_CitationCount_HIndex_noself,0.478234,0.348559,1.37203,0.170064,0.033309
82,hyp2_CitationCount_HIndex_noself,63.998394,2.813808,22.744409,0.0,0.033309
83,hyp2_CitationCount_HIndex_noself,21667.198984,1387.874245,15.611788,0.0,0.033309
84,hyp2_Citation5y_HIndex_noself,1.378703,0.11527,11.960686,0.0,0.056536
85,hyp2_Citation5y_HIndex_noself,0.453415,0.052093,8.703906,0.0,0.056536
86,hyp2_Citation5y_HIndex_noself,14.615063,0.417493,35.006754,0.0,0.056536
87,hyp2_Citation5y_HIndex_noself,-2756.613062,231.344964,-11.915596,0.0,0.056536
88,hyp2_CitationCount_IPG_index,-14.129525,0.412362,-34.264857,0.0,0.031185
89,hyp2_CitationCount_IPG_index,0.649291,0.104036,6.24099,0.0,0.031185
90,hyp2_CitationCount_IPG_index,-15.492605,4.45044,-3.48114,0.0005,0.031185
91,hyp2_CitationCount_IPG_index,28553.119152,828.168832,34.477413,0.0,0.031185
92,hyp2_Citation5y_IPG_index,0.902501,0.10469,8.620706,0.0,0.015659
93,hyp2_Citation5y_IPG_index,0.673291,0.050911,13.224896,0.0,0.015659
94,hyp2_Citation5y_IPG_index,-5.408268,1.08166,-4.999972,0.000001,0.015659
95,hyp2_Citation5y_IPG_index,-1764.60446,209.904321,-8.406709,0.0,0.015659
96,hyp2_CitationCount_HIndex,-14.887529,0.660964,-22.523959,0.0,0.022874
97,hyp2_CitationCount_HIndex,0.526629,0.131606,4.001558,0.000063,0.022874
98,hyp2_CitationCount_HIndex,3.178012,0.284764,11.160144,0.0,0.022874
99,hyp2_CitationCount_HIndex,30043.566933,1328.23654,22.619139,0.0,0.022874
100,hyp2_Citation5y_HIndex,0.521801,0.062848,8.302598,0.0,0.02713
101,hyp2_Citation5y_HIndex,0.1886,0.013822,13.644933,0.0,0.02713
102,hyp2_Citation5y_HIndex,0.828955,0.022588,36.698739,0.0,0.02713
103,hyp2_Citation5y_HIndex,-1011.184156,126.08441,-8.019898,0.0,0.02713
104,hyp2_CitationCount_HIndex_noself,-13.173235,0.314688,-41.861292,0.0,0.032092
105,hyp2_CitationCount_HIndex_noself,0.646148,0.097699,6.613676,0.0,0.032092
106,hyp2_CitationCount_HIndex_noself,29.981403,0.818324,36.637569,0.0,0.032092
107,hyp2_CitationCount_HIndex_noself,26519.076745,632.200017,41.947289,0.0,0.032092
108,hyp2_Citation5y_HIndex_noself,0.600349,0.093612,6.413136,0.0,0.062385
109,hyp2_Citation5y_HIndex_noself,0.105296,0.017251,6.103792,0.0,0.062385
110,hyp2_Citation5y_HIndex_noself,8.652067,0.217631,39.75563,0.0,0.062385
111,hyp2_Citation5y_HIndex_noself,-1190.178687,187.784577,-6.338,0.0,0.062385
112,hyp2_CitationCount_IPG_index,-13.637413,0.426987,-31.938675,0.0,0.035638
113,hyp2_CitationCount_IPG_index,0.732386,0.150662,4.861115,0.000001,0.035638
114,hyp2_CitationCount_IPG_index,-8.926243,5.670748,-1.574086,0.115479,0.035638
115,hyp2_CitationCount_IPG_index,27554.075103,857.606923,32.129026,0.0,0.035638
116,hyp2_Citation5y_IPG_index,0.642458,0.136795,4.696494,0.000003,0.002935
117,hyp2_Citation5y_IPG_index,0.098446,0.023131,4.256032,0.000021,0.002935
118,hyp2_Citation5y_IPG_index,-0.074892,1.736577,-0.043126,0.965601,0.002935
119,hyp2_Citation5y_IPG_index,-1243.906943,274.370572,-4.533675,0.000006,0.002935
120,hyp2_CitationCount_country_count_Health Sciences,-11.707203,0.587378,-19.931303,0.0,0.049267
121,hyp2_CitationCount_country_count_Health Sciences,2.522071,0.547773,4.604226,0.000004,0.049267
122,hyp2_CitationCount_country_count_Health Sciences,36.466466,4.001945,9.112185,0.0,0.049267
123,hyp2_CitationCount_country_count_Health Sciences,23587.413665,1179.38307,19.99979,0.0,0.049267
124,hyp2_Citation5y_country_count_Health Sciences,0.719285,0.203478,3.534951,0.000411,0.099018
125,hyp2_Citation5y_country_count_Health Sciences,0.974518,0.129358,7.533489,0.0,0.099018
126,hyp2_Citation5y_country_count_Health Sciences,15.396208,1.215193,12.669759,0.0,0.099018
127,hyp2_Citation5y_country_count_Health Sciences,-1423.378693,408.088612,-3.487916,0.00049,0.099018
128,hyp2_CitationCount_inst_count_Health Sciences,-12.207708,0.672115,-18.163124,0.0,0.054526
129,hyp2_CitationCount_inst_count_Health Sciences,1.663498,0.668547,2.488229,0.012851,0.054526
130,hyp2_CitationCount_inst_count_Health Sciences,14.803454,1.839483,8.047618,0.0,0.054526
131,hyp2_CitationCount_inst_count_Health Sciences,24605.998414,1349.280325,18.236387,0.0,0.054526
132,hyp2_Citation5y_inst_count_Health Sciences,-0.057451,0.386981,-0.148459,0.881986,-0.031867
133,hyp2_Citation5y_inst_count_Health Sciences,0.406034,0.145352,2.793457,0.005231,-0.031867
134,hyp2_Citation5y_inst_count_Health Sciences,10.305824,0.996268,10.344426,0.0,-0.031867
135,hyp2_Citation5y_inst_count_Health Sciences,126.966789,775.792634,0.163661,0.870004,-0.031867
136,hyp2_CitationCount_gender_percent_Health Sciences,-12.302903,0.968103,-12.708256,0.0,0.025137
137,hyp2_CitationCount_gender_percent_Health Sciences,4.916095,0.673895,7.295048,0.0,0.025137
138,hyp2_CitationCount_gender_percent_Health Sciences,48.139698,36.178652,1.330611,0.183356,0.025137
139,hyp2_CitationCount_gender_percent_Health Sciences,24799.351124,1947.811633,12.731904,0.0,0.025137
140,hyp2_Citation5y_gender_percent_Health Sciences,0.172236,0.215663,0.798634,0.424538,0.099694
141,hyp2_Citation5y_gender_percent_Health Sciences,6.107659,0.2162,28.250102,0.0,0.099694
142,hyp2_Citation5y_gender_percent_Health Sciences,32.354243,7.567337,4.275512,0.000019,0.099694
143,hyp2_Citation5y_gender_percent_Health Sciences,-357.175442,433.13743,-0.824624,0.409622,0.099694
144,hyp2_CitationCount_HIndex_Health Sciences,-11.031273,0.599378,-18.404525,0.0,0.078732
145,hyp2_CitationCount_HIndex_Health Sciences,3.393854,0.510434,6.64896,0.0,0.078732
146,hyp2_CitationCount_HIndex_Health Sciences,4.998473,0.318676,15.685129,0.0,0.078732
147,hyp2_CitationCount_HIndex_Health Sciences,22246.01072,1203.785447,18.480046,0.0,0.078732
148,hyp2_Citation5y_HIndex_Health Sciences,0.262272,0.219366,1.195591,0.231913,0.004491
149,hyp2_Citation5y_HIndex_Health Sciences,4.776188,0.247895,19.266968,0.0,0.004491
150,hyp2_Citation5y_HIndex_Health Sciences,1.481689,0.104228,14.215848,0.0,0.004491
151,hyp2_Citation5y_HIndex_Health Sciences,-524.482038,439.89594,-1.192287,0.233205,0.004491
152,hyp2_CitationCount_HIndex_noself_Health Sciences,-8.297474,0.393118,-21.106821,0.0,0.080431
153,hyp2_CitationCount_HIndex_noself_Health Sciences,4.721944,0.378041,12.490567,0.0,0.080431
154,hyp2_CitationCount_HIndex_noself_Health Sciences,51.621935,1.369708,37.688285,0.0,0.080431
155,hyp2_CitationCount_HIndex_noself_Health Sciences,16647.329651,789.367332,21.089459,0.0,0.080431
156,hyp2_Citation5y_HIndex_noself_Health Sciences,1.479983,0.283144,5.22696,0.0,0.065279
157,hyp2_Citation5y_HIndex_noself_Health Sciences,1.656027,0.227798,7.26971,0.0,0.065279
158,hyp2_Citation5y_HIndex_noself_Health Sciences,21.872245,0.892187,24.515304,0.0,0.065279
159,hyp2_Citation5y_HIndex_noself_Health Sciences,-2990.379746,568.087633,-5.263941,0.0,0.065279
160,hyp2_CitationCount_IPG_index_Health Sciences,-10.018244,0.534746,-18.734571,0.0,0.035271
161,hyp2_CitationCount_IPG_index_Health Sciences,2.886101,0.388396,7.430827,0.0,0.035271
162,hyp2_CitationCount_IPG_index_Health Sciences,-12.283732,5.060157,-2.42754,0.015215,0.035271
163,hyp2_CitationCount_IPG_index_Health Sciences,20248.359352,1073.574457,18.860694,0.0,0.035271
164,hyp2_Citation5y_IPG_index_Health Sciences,0.443188,0.157797,2.808595,0.004986,0.064503
165,hyp2_Citation5y_IPG_index_Health Sciences,1.834637,0.140719,13.03763,0.0,0.064503
166,hyp2_Citation5y_IPG_index_Health Sciences,-3.320893,1.417197,-2.343283,0.019135,0.064503
167,hyp2_Citation5y_IPG_index_Health Sciences,-856.111798,316.307262,-2.706583,0.00681,0.064503
168,hyp2_CitationCount_HIndex_Health Sciences,-10.640087,0.419764,-25.347775,0.0,0.04566
169,hyp2_CitationCount_HIndex_Health Sciences,6.065124,0.444308,13.650718,0.0,0.04566
170,hyp2_CitationCount_HIndex_Health Sciences,1.792131,0.20104,8.914317,0.0,0.04566
171,hyp2_CitationCount_HIndex_Health Sciences,21444.20408,842.923135,25.440284,0.0,0.04566
172,hyp2_Citation5y_HIndex_Health Sciences,0.325806,0.122603,2.657399,0.007878,0.057594
173,hyp2_Citation5y_HIndex_Health Sciences,2.682537,0.104429,25.687684,0.0,0.057594
174,hyp2_Citation5y_HIndex_Health Sciences,0.84027,0.044077,19.063475,0.0,0.057594
175,hyp2_Citation5y_HIndex_Health Sciences,-633.367954,245.928119,-2.575419,0.010016,0.057594
176,hyp2_CitationCount_HIndex_noself_Health Sciences,-10.264547,0.641339,-16.004862,0.0,0.03837
177,hyp2_CitationCount_HIndex_noself_Health Sciences,6.378486,0.70839,9.004206,0.0,0.03837
178,hyp2_CitationCount_HIndex_noself_Health Sciences,19.585114,1.675546,11.688793,0.0,0.03837
179,hyp2_CitationCount_HIndex_noself_Health Sciences,20637.324546,1287.624804,16.027436,0.0,0.03837
180,hyp2_Citation5y_HIndex_noself_Health Sciences,0.275486,0.26073,1.056597,0.290717,0.023147
181,hyp2_Citation5y_HIndex_noself_Health Sciences,3.728481,0.265465,14.045072,0.0,0.023147
182,hyp2_Citation5y_HIndex_noself_Health Sciences,7.381604,0.60841,12.132605,0.0,0.023147
183,hyp2_Citation5y_HIndex_noself_Health Sciences,-561.935773,522.873384,-1.074707,0.282527,0.023147
184,hyp2_CitationCount_IPG_index_Health Sciences,-12.844701,0.584416,-21.978694,0.0,0.033365
185,hyp2_CitationCount_IPG_index_Health Sciences,4.551857,0.591933,7.689822,0.0,0.033365
186,hyp2_CitationCount_IPG_index_Health Sciences,-5.862824,6.409202,-0.914751,0.360328,0.033365
187,hyp2_CitationCount_IPG_index_Health Sciences,25908.19548,1173.381693,22.079938,0.0,0.033365
188,hyp2_Citation5y_IPG_index_Health Sciences,0.246701,0.079908,3.087305,0.002027,0.046255
189,hyp2_Citation5y_IPG_index_Health Sciences,3.62477,0.086236,42.033265,0.0,0.046255
190,hyp2_Citation5y_IPG_index_Health Sciences,-0.478298,0.822706,-0.581372,0.561006,0.046255
191,hyp2_Citation5y_IPG_index_Health Sciences,-475.572644,160.207461,-2.96848,0.003002,0.046255
192,hyp2_CitationCount_country_count_Physical Scie...,-15.130982,0.541107,-27.963029,0.0,0.046744
193,hyp2_CitationCount_country_count_Physical Scie...,-0.175589,0.261222,-0.672183,0.501476,0.046744
194,hyp2_CitationCount_country_count_Physical Scie...,13.746769,4.93171,2.787424,0.005318,0.046744
195,hyp2_CitationCount_country_count_Physical Scie...,30538.208281,1087.442678,28.082591,0.0,0.046744
196,hyp2_Citation5y_country_count_Physical Sciences,0.786788,0.080034,9.83067,0.0,0.006907
197,hyp2_Citation5y_country_count_Physical Sciences,-0.013996,0.015628,-0.895609,0.370488,0.006907
198,hyp2_Citation5y_country_count_Physical Sciences,5.303395,0.637877,8.314134,0.0,0.006907
199,hyp2_Citation5y_country_count_Physical Sciences,-1546.424673,160.532125,-9.633117,0.0,0.006907
200,hyp2_CitationCount_inst_count_Physical Sciences,-13.886645,0.785932,-17.669026,0.0,0.024094
201,hyp2_CitationCount_inst_count_Physical Sciences,0.385467,0.235055,1.639904,0.101032,0.024094
202,hyp2_CitationCount_inst_count_Physical Sciences,1.088924,2.373934,0.4587,0.646452,0.024094
203,hyp2_CitationCount_inst_count_Physical Sciences,28051.444368,1579.782464,17.756523,0.0,0.024094
204,hyp2_Citation5y_inst_count_Physical Sciences,0.900366,0.12669,7.106836,0.0,0.005302
205,hyp2_Citation5y_inst_count_Physical Sciences,-0.171491,0.064167,-2.672588,0.007541,0.005302
206,hyp2_Citation5y_inst_count_Physical Sciences,2.239284,0.405149,5.527067,0.0,0.005302
207,hyp2_Citation5y_inst_count_Physical Sciences,-1769.807597,254.15759,-6.963426,0.0,0.005302
208,hyp2_CitationCount_gender_percent_Physical Sci...,-15.123379,0.636942,-23.74374,0.0,0.036381
209,hyp2_CitationCount_gender_percent_Physical Sci...,-0.023651,0.153905,-0.153675,0.877867,0.036381
210,hyp2_CitationCount_gender_percent_Physical Sci...,-5.69971,21.630175,-0.263507,0.792163,0.036381
211,hyp2_CitationCount_gender_percent_Physical Sci...,30546.457735,1284.210846,23.78617,0.0,0.036381
212,hyp2_Citation5y_gender_percent_Physical Sciences,0.980727,0.112332,8.730581,0.0,0.00641
213,hyp2_Citation5y_gender_percent_Physical Sciences,0.102142,0.013952,7.321033,0.0,0.00641
214,hyp2_Citation5y_gender_percent_Physical Sciences,9.509387,3.624779,2.623439,0.008717,0.00641
215,hyp2_Citation5y_gender_percent_Physical Sciences,-1934.24027,225.942185,-8.560775,0.0,0.00641
216,hyp2_CitationCount_HIndex_Physical Sciences,-15.117792,0.638468,-23.678229,0.0,0.035889
217,hyp2_CitationCount_HIndex_Physical Sciences,0.618624,0.101643,6.086228,0.0,0.035889
218,hyp2_CitationCount_HIndex_Physical Sciences,3.822737,0.392046,9.750735,0.0,0.035889
219,hyp2_CitationCount_HIndex_Physical Sciences,30512.590004,1283.862192,23.76625,0.0,0.035889
220,hyp2_Citation5y_HIndex_Physical Sciences,0.937848,0.105728,8.870351,0.0,-0.024715
221,hyp2_Citation5y_HIndex_Physical Sciences,0.854126,0.031388,27.211657,0.0,-0.024715
222,hyp2_Citation5y_HIndex_Physical Sciences,0.546822,0.066634,8.206368,0.0,-0.024715
223,hyp2_Citation5y_HIndex_Physical Sciences,-1850.882749,212.244989,-8.720502,0.0,-0.024715
224,hyp2_CitationCount_HIndex_noself_Physical Scie...,-11.451635,0.567829,-20.167404,0.0,0.034462
225,hyp2_CitationCount_HIndex_noself_Physical Scie...,-0.153367,0.258132,-0.594141,0.552422,0.034462
226,hyp2_CitationCount_HIndex_noself_Physical Scie...,53.483168,2.449405,21.83517,0.0,0.034462
227,hyp2_CitationCount_HIndex_noself_Physical Scie...,23045.940449,1141.655011,20.186431,0.0,0.034462
228,hyp2_Citation5y_HIndex_noself_Physical Sciences,1.468989,0.056427,26.033551,0.0,0.059653
229,hyp2_Citation5y_HIndex_noself_Physical Sciences,0.150277,0.01329,11.307938,0.0,0.059653
230,hyp2_Citation5y_HIndex_noself_Physical Sciences,11.965217,0.21159,56.549088,0.0,0.059653
231,hyp2_Citation5y_HIndex_noself_Physical Sciences,-2933.934064,113.28971,-25.897622,0.0,0.059653
232,hyp2_CitationCount_IPG_index_Physical Sciences,-13.453195,0.497302,-27.052351,0.0,0.032139
233,hyp2_CitationCount_IPG_index_Physical Sciences,0.163994,0.221126,0.741632,0.458312,0.032139
234,hyp2_CitationCount_IPG_index_Physical Sciences,-12.644143,5.803642,-2.178657,0.02936,0.032139

In [0]:
descriptives_output_df

,model,subjareas,mean,sd,sample,median,iqr_25,iqr_75
0,hyp1a,Health Sciences,9.819035,16.976186,39759,7,4,12
1,hyp1a,Physical Sciences,12.530522,64.194176,68131,8,4,15
2,hyp1a,Multidisciplinary,8.628452,42.429613,5504,6,4,9
3,hyp1a,Social Sciences,5.034569,6.673358,16778,4,2,6
4,hyp1a,Life Sciences,10.733374,12.479251,48945,8,4,13
5,hyp1b_CitationCount,Health Sciences,128.641289,516.389834,39759,34,9,100
6,hyp1b_CitationCount,Physical Sciences,127.04961,763.368957,68131,27,7,85
7,hyp1b_CitationCount,Multidisciplinary,392.900073,1271.384244,5504,83,15,359
8,hyp1b_CitationCount,Social Sciences,164.664382,740.622985,16778,26,5,102
9,hyp1b_CitationCount,Life Sciences,137.362059,754.269326,48945,37,11,102
10,hyp1b_Citation5y,Health Sciences,35.45889,117.678626,39759,13,4,32
11,hyp1b_Citation5y,Physical Sciences,30.283131,98.682659,68131,12,4,29
12,hyp1b_Citation5y,Multidisciplinary,100.476744,241.72837,5504,34,10,103
13,hyp1b_Citation5y,Social Sciences,20.355108,47.461236,16778,9,3,22
14,hyp1b_Citation5y,Life Sciences,34.453325,153.015213,48945,15,6,33

PROJECT DETAILS:
Project identifier: proj_050_teamscience
Cluster data access level: fulldata

EXECUTION DETAILS:
Spark version: 11.3.x-aarch64-scala2.12,
Cluster Node Type: r6gd.2xlarge,
Driver Node Type: r6gd.2xlarge,
Worker Node Type: r6gd.2xlarge

DATA SNAPSHOT DETAILS:
This notebook uses the latest snapshot date for this version: "v008.20230509104116/", (09 May 2023)

 The following are the Scopus snapshot dates available for datasets at v008:
['v008.20220314092239/', 'v008.20220906063204/', 'v008.20221021151538/', 'v008.20230509104116/']
(If you want to use a different snapshot, in the first cell of your notebook, set the variable `custom_snapshot_date` to one of the options listed above (string data type))

DATA SAMPLE DETAILS:
Setting paths to run on full datasets (100% Scopus publication volume)

In [0]:
model_output_df.to_csv('/dbfs/Projects/proj_050_teamsci/model_output_200723_part1.csv')
descriptives_output_df.to_csv('/dbfs/Projects/proj_050_teamsci/descriptives_output_df_200723_part1.csv')