In [0]:
# set whether normal process or being run by Elsevier supporters
permissions = 'fulldata' # default or fulldata
# set the project name
project_name = 'proj_050_teamscience'  # This is the folder name that you work in, e.g. 'test_project_1'

In [0]:
#Alick: I'll switch to the latest snapshot (v008) - wording there is confusing! 
#%run /Snippets/header_latest

In [0]:
%run /Snippets/header_008

## Python Libraries and Functions

In [0]:
# libraries 
from pyspark.sql.functions import col, count, explode, array, mean, stddev, filter, percentile_approx, arrays_zip, size, array_distinct, sum, reverse, collect_list, array_sort, posexplode, max, arrays_overlap, lit, when, cast
from pyspark.ml.feature import VectorAssembler
from pyspark.ml.regression import LinearRegression
import pandas as pd
import matplotlib.pyplot as plt
from pyspark.sql import Window
from pyspark.ml.feature import StringIndexer

# make a DF to store everything
model_output_df = pd.DataFrame(columns = ["model", "coef", "se", "t", "p", "r2"])
descriptives_output_df = pd.DataFrame(columns = ["model", "subjareas", "mean", "sd", "sample", "median", "iqr_25", "iqr_75"])

# model summary print out 
def modelsummary(model, hyp_model, df):
    import numpy as np
    print ("Note: the last rows are the information for Intercept")
    print ("##","-------------------------------------------------")
    print ("##","  Estimate   |   Std.Error | t Values  |  P-value")
    coef = np.append(list(model.coefficients),model.intercept)
    Summary=model.summary

    for i in range(len(Summary.pValues)):
        print ("##",'{:10.6f}'.format(coef[i]),\
        '{:10.6f}'.format(Summary.coefficientStandardErrors[i]),\
        '{:8.3f}'.format(Summary.tValues[i]),\
        '{:10.6f}'.format(Summary.pValues[i]))
        # store the data 
        row = pd.DataFrame({"model": hyp_model, "coef": coef[i], "se": Summary.coefficientStandardErrors[i], 
               "t": Summary.tValues[i], "p": Summary.pValues[i], "r2": Summary.r2}, index = [0])
        df = pd.concat([df, row], ignore_index = True, axis = 0)

    print ("##",'---')
    print ("##","Mean squared error: % .6f" \
           % Summary.meanSquaredError, ", RMSE: % .6f" \
           % Summary.rootMeanSquaredError )
    print ("##","Multiple R-squared: %f" % Summary.r2, ", \
            Total iterations: %i"% Summary.totalIterations)
    return(df)

PROJECT DETAILS:
Project identifier: proj_050_teamscience
Cluster data access level: fulldata

# Research Question 2

What characteristics of team composition have the greatest influence on article metrics? 

Author independent variables: Author characteristics include affiliation country, affiliation/institution, h-index, gender, and gender ratio. We will transform the affiliation country into a count variable of the number of unique countries. Similarly, we will transform the affiliation/institutions into a count of the number of different affiliations across authors. We will use the h-index of the first and last authors for each article. We will use h-index with and without self-citation if this metric is available through the ICSR system. Last, Elsevier has noted that their inferred gender column has a 97% accuracy, and we will use inferred gender of the first and last authors for each article. From this variable, we will additionally calculate the gender ratio (percent male) as a single variable for each article.

In [0]:
df_ani = spark.read.format("parquet").load(basePath+tablename_ani)
df_ani_smaller = df_ani.filter(df_ani.Year > 1969)\
  .filter(df_ani.publication_type == "ar")\
  .sample(False, .25, 8675309) 

df_fwci = spark.read.format("parquet").load(fwci_parquet_path)

In [0]:
# calculate variables, load tables
# gender
df_gender = spark.read.format("parquet").load(basePath+tablename_gender_inference)

# gender ratio
gender_summary = df_ani_smaller.select("Eid", "Au.auid")\
  .withColumn("auid", explode("auid"))\
  .join(df_gender.select("auid", "Inferred_Probable_Gender"), "auid", "left")\
  .groupBy("Eid", "Inferred_Probable_Gender")\
  .agg(count("auid").alias("author_count"))\
  .withColumn("gender_percent", col("author_count")/sum("author_count").over(Window.partitionBy("Eid")))\
  .withColumn("team_size", sum("author_count").over(Window.partitionBy("Eid")))\
  .filter(col("Inferred_Probable_Gender") == "male")\
  .drop("Inferred_Probable_Gender", "author_count")

# display(gender_summary)

In [0]:
# merge all data needed
df_hyp2 = df_ani_smaller.select("Eid", "Year", "Au.Authorseq", "Af.affiliation_country", "Af.affiliation_ids", "ASJC", "CitationCount", "Au.auid")\
  .withColumn("country_count", size(array_distinct("affiliation_country")))\
  .withColumn("inst_count", size(array_distinct("affiliation_ids")))\
  .withColumn("auth_combo", arrays_zip("Authorseq", "auid"))\
  .withColumn("auth_combo", explode("auth_combo"))\
  .select("Eid", "Year", "country_count", "inst_count", "ASJC", "CitationCount", col("auth_combo.Authorseq").alias("Authorseq"), col("auth_combo.auid").alias("auid"))\
  .join(df_gender.select("auid", "Inferred_Probable_Gender"), "auid", "left")\
  .join(df_fwci.select("Eid", "Citations_5y"), "Eid", "left")\
  .join(gender_summary, "Eid", "left")
  
# display(df_hyp2)

In [0]:
# calculate h-index for only those we need
df_authors = df_hyp2.select("Authorseq", "auid", "team_size")\
	.filter((col("Authorseq") == 1) | (col("Authorseq") == col("team_size")))

In [0]:
windowspec = Window.partitionBy('auid').orderBy(func.col('citation_count').desc())

df_hindex =(df_ani
            .select('eid', func.col('Year').alias('year_of_citation'),func.array_distinct('references').alias('references'))
            .withColumn('cited_document', func.explode('references'))
            .join(df_ani.select(func.col('Eid').alias('cited_document'),
                                func.col('Year').alias('cited_doc_pub_year'),
                                func.col('Au.auid').alias('cited_authors')),
                     on = 'cited_document',
                     how = 'inner')
            .groupBy('cited_document','cited_doc_pub_year','cited_authors')
            .agg(func.countDistinct('Eid').alias('citation_count'))

            # h index window method
            .withColumn('auid', func.explode('cited_authors'))
            .withColumn('citation_rank_by_author', func.row_number().over(windowspec))
            .withColumn('rank_when_under_hgraph_line', func.when( func.col('citation_count') >= func.col('citation_rank_by_author'), func.col('citation_rank_by_author')))
            .groupBy('auid')
            .agg(func.max('rank_when_under_hgraph_line').alias('HIndex')) )

# now join against df_hyp2
df_hyp2 = df_hyp2.join(df_hindex, on='auid', how='left')

In [0]:
'''
# leave this as df_ani so you get all their publications
df_hindex = df_ani.withColumn('auid', explode ('Au.auid'))\
	.select('Eid', 'auid', 'Year', 'Title', 'CitationCount')\
	.join(df_authors, "auid", "right")\
	.groupBy("auid")\
	.agg(collect_list('CitationCount').alias('CitationsList'))\
	.withColumn('CitationsList', reverse(array_sort('CitationsList')))\
	.select('auid', posexplode('CitationsList').alias('CitationPosition', 'CitationCount'))\
	.filter(col('CitationCount') >= (col('CitationPosition') + 1))\
	.groupBy('auid')\
	.agg(max('CitationPosition').alias('HIndexMinus1'))\
	.withColumn('HIndex', col('HIndexMinus1') + 1)\
	.drop(col('HIndexMinus1'))
     
# display(df_hindex)

df_hyp2 = df_hyp2.join(df_hindex, "auid", "left")

# display(df_hyp2)'''

Out[14]: '\n# leave this as df_ani so you get all their publications\ndf_hindex = df_ani.withColumn(\'auid\', explode (\'Au.auid\'))\t.select(\'Eid\', \'auid\', \'Year\', \'Title\', \'CitationCount\')\t.join(df_authors, "auid", "right")\t.groupBy("auid")\t.agg(collect_list(\'CitationCount\').alias(\'CitationsList\'))\t.withColumn(\'CitationsList\', reverse(array_sort(\'CitationsList\')))\t.select(\'auid\', posexplode(\'CitationsList\').alias(\'CitationPosition\', \'CitationCount\'))\t.filter(col(\'CitationCount\') >= (col(\'CitationPosition\') + 1))\t.groupBy(\'auid\')\t.agg(max(\'CitationPosition\').alias(\'HIndexMinus1\'))\t.withColumn(\'HIndex\', col(\'HIndexMinus1\') + 1)\t.drop(col(\'HIndexMinus1\'))\n     \n# display(df_hindex)\n\ndf_hyp2 = df_hyp2.join(df_hindex, "auid", "left")\n\n# display(df_hyp2)'

In [0]:
windowspec = Window.partitionBy('auid').orderBy(func.col('nonselfcitationcount').desc())

df_hindex_no_sc =(df_ani
                  .select('eid', 
                          func.col('Au.auid').alias('citing_authors'),
                          func.col('Year').alias('year_of_citation'),
                          func.array_distinct('references').alias('references'))
                  .withColumn('cited_document', func.explode('references'))
                  .join(df_ani.select(func.col('Eid').alias('cited_document'),
                                      func.col('Year').alias('cited_doc_pub_year'),
                                      func.col('Au.auid').alias('cited_authors')),
                          on = 'cited_document',
                          how = 'inner')
                  .withColumn('self_citation_tf', arrays_overlap('citing_authors', 'cited_authors'))
                  .groupBy('cited_document','cited_doc_pub_year','cited_authors')
                  .agg(func.sum(
                    func.when(func.col('self_citation_tf'), func.lit(0)).otherwise(func.lit(1))).alias('nonselfcitationcount'))
                  
                  # h index window method
                  .withColumn('auid', func.explode('cited_authors'))
                  .withColumn('citation_rank_by_author', func.row_number().over(windowspec))
                  .withColumn('rank_when_under_hgraph_line', func.when( func.col('nonselfcitationcount') >= func.col('citation_rank_by_author'), func.col('citation_rank_by_author')))
                  .groupBy('auid')
                  .agg(func.max('rank_when_under_hgraph_line').alias('HIndex_noself')) )

# now join against df_hyp2
df_hyp2 = df_hyp2.join(df_hindex_no_sc, on='auid', how='left')

In [0]:
'''# no self citation h-index
df_from_corpus = (
  df_ani
  .select(col('eid').alias('from_eid'),
          col('year').alias('from_year'),
          col('Au.auid').alias('from_auids'), 
          size('Au').alias('from_n_Au'),
          col('CitationCount').alias('from_CC'), 
          'references') 
  .withColumn('references_to', explode('references'))
  .withColumnRenamed('year','from_year')
)

# metadata for everything that is cited
df_references_from_to = (
  df_from_corpus
  .join(df_ani
        # which fields to retain of the "to" publication, renaming for clarity
        .select(col('Au.auid').alias("to_auids"), col('year').alias('to_year'), col('eid'), size('Au').alias('to_n_A')),
        #join the "from" article's references to the "to" articles' IDs
        col('references_to') == df_ani['eid'], 'left')
        .withColumnRenamed('eid', 'to_eid')
        .withColumn('self_citation_tf', arrays_overlap('from_auids', 'to_auids'))
)

df_self_cc_counts = (
  df_references_from_to
  .groupBy('to_eid', 'to_auids') 
  .agg(count(lit(True)).alias('fullcitationcount'),
      sum(when(col('self_citation_tf'), lit(1)).otherwise(lit(0))).alias('selfcitationcount'),
      sum(when(col('self_citation_tf'), lit(0)).otherwise(lit(1))).alias('nonselfcitationcount'))
)

# display(df_self_cc_counts)

df_hindex = df_self_cc_counts.withColumn('auid', explode('to_auids'))\
	.groupBy("auid")\
	.agg(collect_list('nonselfcitationcount').alias('CitationsList'))\
	.withColumn('CitationsList', reverse(array_sort('CitationsList')))\
	.select ('auid', posexplode('CitationsList').alias('CitationPosition', 'nonselfcitationcount'))\
	.filter(col('nonselfcitationcount') >= (col('CitationPosition') + 1))\
	.groupBy('auid')\
	.agg(max('CitationPosition').alias('HIndexMinus1'))\
	.withColumn('HIndex_noself', col('HIndexMinus1') + 1)\
	.drop(col('HIndexMinus1'))
     
# display(df_hindex)

df_hyp2 = df_hyp2.join(df_hindex, "auid", "left")

# display(df_hyp2)'''

Out[16]: '# no self citation h-index\ndf_from_corpus = (\n  df_ani\n  .select(col(\'eid\').alias(\'from_eid\'),\n          col(\'year\').alias(\'from_year\'),\n          col(\'Au.auid\').alias(\'from_auids\'), \n          size(\'Au\').alias(\'from_n_Au\'),\n          col(\'CitationCount\').alias(\'from_CC\'), \n          \'references\') \n  .withColumn(\'references_to\', explode(\'references\'))\n  .withColumnRenamed(\'year\',\'from_year\')\n)\n\n# metadata for everything that is cited\ndf_references_from_to = (\n  df_from_corpus\n  .join(df_ani\n        # which fields to retain of the "to" publication, renaming for clarity\n        .select(col(\'Au.auid\').alias("to_auids"), col(\'year\').alias(\'to_year\'), col(\'eid\'), size(\'Au\').alias(\'to_n_A\')),\n        #join the "from" article\'s references to the "to" articles\' IDs\n        col(\'references_to\') == df_ani[\'eid\'], \'left\')\n        .withColumnRenamed(\'eid\', \'to_eid\')\n        .withColumn(\'self_citation_tf\', arrays_overlap(\'from_auids\', \'to_auids\'))\n)\n\ndf_self_cc_counts = (\n  df_references_from_to\n  .groupBy(\'to_eid\', \'to_auids\') \n  .agg(count(lit(True)).alias(\'fullcitationcount\'),\n      sum(when(col(\'self_citation_tf\'), lit(1)).otherwise(lit(0))).alias(\'selfcitationcount\'),\n      sum(when(col(\'self_citation_tf\'), lit(0)).otherwise(lit(1))).alias(\'nonselfcitationcount\'))\n)\n\n# display(df_self_cc_counts)\n\ndf_hindex = df_self_cc_counts.withColumn(\'auid\', explode(\'to_auids\'))\t.groupBy("auid")\t.agg(collect_list(\'nonselfcitationcount\').alias(\'CitationsList\'))\t.withColumn(\'CitationsList\', reverse(array_sort(\'CitationsList\')))\t.select (\'auid\', posexplode(\'CitationsList\').alias(\'CitationPosition\', \'nonselfcitationcount\'))\t.filter(col(\'nonselfcitationcount\') >= (col(\'CitationPosition\') + 1))\t.groupBy(\'auid\')\t.agg(max(\'CitationPosition\').alias(\'HIndexMinus1\'))\t.withColumn(\'HIndex_noself\', col(\'HIndexMinus1\') + 1)\t.drop(col(\'HIndexMinus1\'))\n     \n# display(df_hindex)\n\ndf_hyp2 = df_hyp2.join(df_hindex, "auid", "left")\n\n# display(df_hyp2)'

In [0]:
# create string index for Inferred Probable Gender 
indexer = StringIndexer(inputCol="Inferred_Probable_Gender", outputCol="IPG_index")
df_hyp2 = indexer.setHandleInvalid("skip").fit(df_hyp2).transform(df_hyp2)

# display(df_hyp2)

### Overall Summary 

For this research question, we will continue to use the model from the previous research question and add other article metrics to determine their contribution to the model. Our hypothesis is that each variable has an impact on the metrics variables (non-directional). Each author independent variable will be modeled separately and compared using confidence intervals as described above for which variable had the strongest impact on publication metrics. 

Using the linear model from the previous research question, we will add each author independent variable (affiliation country count, affiliation/institution count, h-index, gender, and gender ratio) in separate models to calculate their slope. We will determine if these slopes were important by examining if their confidence interval was greater than zero. We will then compare each slope to other slopes to see if their confidence intervals overlap. We have to examine the effects of each author metric separately. When examining first and/or last author information, the single author paper presents a unique problem because they are both first and last author. Therefore, these cannot be included in the same model. In order not to use the same variance twice, single author papers will be treated as first author only, and NA for last author analyses. If these were included in the same model, all single author papers would be dropped, which would bias the results.

In [0]:
# list of IVs for unique analyses 
independent_vars = ["country_count", "inst_count", "gender_percent", 
                   "HIndex", "HIndex_noself", "IPG_index", 
                   "2HIndex", "2HIndex_noself", "2IPG_index"]

# drop all the nulls in Y
df_hyp2 = df_hyp2.where(col("CitationCount").isNotNull())

In [0]:
df_hyp2.cache().display()

In [0]:
# loop over all the variables
for vars in independent_vars:
  # citations overall 
  # create dataframe, for these use unique Eids
  if (vars == "country_count") | (vars == "inst_count") | (vars == "gender_percent"):
    df_hyp2_overall = df_hyp2.dropDuplicates(['Eid'])
  elif (vars == "HIndex") | (vars == "HIndex_noself"):
    df_hyp2_overall = df_hyp2.filter((col("Authorseq") == 1))
  elif (vars == "IPG_index"):
    df_hyp2_overall = df_hyp2.filter((col("Authorseq") == 1))\
      .filter((col("Inferred_Probable_Gender") == "male") | (col("Inferred_Probable_Gender") == "female"))
  elif (vars == "2HIndex") | (vars == "2HIndex_noself"):
    df_hyp2_overall = df_hyp2.filter((col("Authorseq") == col("team_size")))
    vars = vars[1:]
  elif (vars == "2IPG_index"):
    df_hyp2_overall = df_hyp2.filter((col("Authorseq") == col("team_size")))\
      .filter((col("Inferred_Probable_Gender") == "male") | (col("Inferred_Probable_Gender") == "female"))
    vars = vars[1:]    

  # should drop nulls in X
  vectorAssembler = VectorAssembler(inputCols = ['Year', 'team_size', vars], outputCol = "pub_year")
  df_hyp2_overall = vectorAssembler.setHandleInvalid("skip").transform(df_hyp2_overall)
  df_hyp2_overall.cache()
  
  print(vars)
  print("\n----------\n")
  
  # put in the features X and prediction Y
  lr = LinearRegression(featuresCol = 'pub_year', labelCol = 'CitationCount')
  lr_model = lr.fit(df_hyp2_overall)
  model_output_df = modelsummary(lr_model, ("hyp2_CitationCount_"+vars), model_output_df)
  
  ## citations_5y
  # same DF just drop NULL citations_5y and newer articles 
  # if no citationcount then don't trust citations_5y
  df_hyp2_overall = df_hyp2_overall.where(col("Citations_5y").isNotNull())\
    .filter(col("Year") < 2017)
  
  # put in the features X and prediction Y
  lr = LinearRegression(featuresCol = 'pub_year', labelCol = 'Citations_5y')
  lr_model = lr.fit(df_hyp2_overall)
  model_output_df = modelsummary(lr_model, ("hyp2_Citation5y_"+vars), model_output_df)

  df_hyp2_overall.unpersist()

country_count

----------

Note: the last rows are the information for Intercept
## -------------------------------------------------
##   Estimate   |   Std.Error | t Values  |  P-value
##  -0.465274   0.002255 -206.294   0.000000
##  -0.022046   0.001588  -13.879   0.000000
##   7.458726   0.040440  184.439   0.000000
## 949.380812   4.517021  210.179   0.000000
## ---
## Mean squared error:  9875.393682 , RMSE:  99.375015
## Multiple R-squared: 0.006760 ,             Total iterations: 0
Note: the last rows are the information for Intercept
## -------------------------------------------------
##   Estimate   |   Std.Error | t Values  |  P-value
##   0.221818   0.000750  295.861   0.000000
##   0.009434   0.000571   16.520   0.000000
##   4.461241   0.014662  304.281   0.000000
## -440.198178   1.497479 -293.959   0.000000
## ---
## Mean squared error:  641.953275 , RMSE:  25.336797
## Multiple R-squared: 0.031311 ,             Total iterations: 0
inst_count

----------

Note: the last rows are the information for Intercept
## -------------------------------------------------
##   Estimate   |   Std.Error | t Values  |  P-value
##  -0.492492   0.002281 -215.950   0.000000
##  -0.156769   0.002031  -77.183   0.000000
##   2.757967   0.014971  184.223   0.000000
## 1008.468323   4.569144  220.713   0.000000
## ---
## Mean squared error:  9875.467416 , RMSE:  99.375386
## Multiple R-squared: 0.006752 ,             Total iterations: 0
Note: the last rows are the information for Intercept
## -------------------------------------------------
##   Estimate   |   Std.Error | t Values  |  P-value
##   0.197210   0.000759  259.889   0.000000
##  -0.108553   0.000767 -141.561   0.000000
##   2.080840   0.006028  345.220   0.000000
## -388.818160   1.516042 -256.469   0.000000
## ---
## Mean squared error:  639.765352 , RMSE:  25.293583
## Multiple R-squared: 0.034612 ,             Total iterations: 0
gender_percent

----------

Note: the last rows are the information for Intercept
## -------------------------------------------------
##   Estimate   |   Std.Error | t Values  |  P-value
##  -0.417073   0.002300 -181.298   0.000000
##   0.110898   0.001416   78.311   0.000000
##  -1.945399   0.112516  -17.290   0.000000
## 862.903342   4.629993  186.372   0.000000
## ---
## Mean squared error:  9906.770235 , RMSE:  99.532760
## Multiple R-squared: 0.003604 ,             Total iterations: 0
Note: the last rows are the information for Intercept
## -------------------------------------------------
##   Estimate   |   Std.Error | t Values  |  P-value
##   0.243836   0.000759  321.087   0.000000
##   0.089239   0.000508  175.820   0.000000
##  -2.236538   0.033723  -66.322   0.000000
## -477.646237   1.522988 -313.625   0.000000
## ---
## Mean squared error:  649.318109 , RMSE:  25.481721
## Multiple R-squared: 0.020197 ,             Total iterations: 0
HIndex

----------

Note: the last rows are the information for Intercept
## -------------------------------------------------
##   Estimate   |   Std.Error | t Values  |  P-value
##  -0.118855   0.002468  -48.154   0.000000
##   0.067646   0.001742   38.833   0.000000
##   0.951383   0.001849  514.666   0.000000
## 248.806216   4.959110   50.172   0.000000
## ---
## Mean squared error:  10122.961436 , RMSE:  100.612929
## Multiple R-squared: 0.029879 ,             Total iterations: 0
Note: the last rows are the information for Intercept
## -------------------------------------------------
##   Estimate   |   Std.Error | t Values  |  P-value
##   0.311830   0.000797  391.056   0.000000
##   0.088644   0.000633  140.071   0.000000
##   0.239571   0.000506  473.685   0.000000
## -619.453921   1.596838 -387.925   0.000000
## ---
## Mean squared error:  657.285929 , RMSE:  25.637588
## Multiple R-squared: 0.048732 ,             Total iterations: 0
HIndex_noself

----------

Note: the last rows are the information for Intercept
## -------------------------------------------------
##   Estimate   |   Std.Error | t Values  |  P-value
##  -0.085779   0.002484  -34.537   0.000000
##   0.074600   0.001742   42.819   0.000000
##   1.094688   0.002048  534.430   0.000000
## 181.933891   4.990353   36.457   0.000000
## ---
## Mean squared error:  10139.708459 , RMSE:  100.696119
## Multiple R-squared: 0.031889 ,             Total iterations: 0
Note: the last rows are the information for Intercept
## -------------------------------------------------
##   Estimate   |   Std.Error | t Values  |  P-value
##   0.318835   0.000799  398.811   0.000000
##   0.090972   0.000632  143.869   0.000000
##   0.271586   0.000558  486.794   0.000000
## -633.577784   1.601068 -395.722   0.000000
## ---
## Mean squared error:  657.082833 , RMSE:  25.633627
## Multiple R-squared: 0.050449 ,             Total iterations: 0
IPG_index

----------

Note: the last rows are the information for Intercept
## -------------------------------------------------
##   Estimate   |   Std.Error | t Values  |  P-value
##  -0.437465   0.002808 -155.816   0.000000
##   0.158903   0.002109   75.358   0.000000
##   1.943423   0.046601   41.704   0.000000
## 902.018599   5.625434  160.347   0.000000
## ---
## Mean squared error:  10926.839222 , RMSE:  104.531523
## Multiple R-squared: 0.003717 ,             Total iterations: 0
Note: the last rows are the information for Intercept
## -------------------------------------------------
##   Estimate   |   Std.Error | t Values  |  P-value
##   0.234508   0.000905  259.023   0.000000
##   0.099453   0.000656  151.516   0.000000
##   1.000886   0.014347   69.764   0.000000
## -460.772656   1.809785 -254.601   0.000000
## ---
## Mean squared error:  685.296082 , RMSE:  26.178160
## Multiple R-squared: 0.018942 ,             Total iterations: 0
HIndex

----------

Note: the last rows are the information for Intercept
## -------------------------------------------------
##   Estimate   |   Std.Error | t Values  |  P-value
##  -0.428087   0.002375 -180.244   0.000000
##   0.058917   0.001515   38.891   0.000000
##   0.671773   0.001233  544.857   0.000000
## 866.230439   4.765696  181.764   0.000000
## ---
## Mean squared error:  10022.501193 , RMSE:  100.112443
## Multiple R-squared: 0.033085 ,             Total iterations: 0
Note: the last rows are the information for Intercept
## -------------------------------------------------
##   Estimate   |   Std.Error | t Values  |  P-value
##   0.226092   0.000788  286.957   0.000000
##   0.068689   0.000535  128.388   0.000000
##   0.226220   0.000356  635.396   0.000000
## -449.888346   1.575871 -285.486   0.000000
## ---
## Mean squared error:  648.101694 , RMSE:  25.457842
## Multiple R-squared: 0.070800 ,             Total iterations: 0
HIndex_noself

----------

Note: the last rows are the information for Intercept
## -------------------------------------------------
##   Estimate   |   Std.Error | t Values  |  P-value
##  -0.411716   0.002381 -172.912   0.000000
##   0.064399   0.001515   42.506   0.000000
##   0.753263   0.001347  559.056   0.000000
## 833.154735   4.778110  174.369   0.000000
## ---
## Mean squared error:  10034.239463 , RMSE:  100.171051
## Multiple R-squared: 0.034622 ,             Total iterations: 0
Note: the last rows are the information for Intercept
## -------------------------------------------------
##   Estimate   |   Std.Error | t Values  |  P-value
##   0.231804   0.000788  294.097   0.000000
##   0.071115   0.000535  133.000   0.000000
##   0.250192   0.000388  645.237   0.000000
## -461.341270   1.576578 -292.622   0.000000
## ---
## Mean squared error:  648.025961 , RMSE:  25.456354
## Multiple R-squared: 0.072485 ,             Total iterations: 0
IPG_index

----------

Note: the last rows are the information for Intercept
## -------------------------------------------------
##   Estimate   |   Std.Error | t Values  |  P-value
##  -0.427454   0.002708 -157.829   0.000000
##   0.119744   0.001737   68.938   0.000000
##   0.843494   0.053566   15.747   0.000000
## 882.757558   5.428821  162.606   0.000000
## ---
## Mean squared error:  10223.505441 , RMSE:  101.111352
## Multiple R-squared: 0.003743 ,             Total iterations: 0
Note: the last rows are the information for Intercept
## -------------------------------------------------
##   Estimate   |   Std.Error | t Values  |  P-value
##   0.245036   0.000898  272.763   0.000000
##   0.090516   0.000600  150.982   0.000000
##   0.496223   0.017238   28.786   0.000000
## -481.520205   1.796343 -268.056   0.000000
## ---
## Mean squared error:  674.803481 , RMSE:  25.976980
## Multiple R-squared: 0.018536 ,             Total iterations: 0

###Summary By Subject Area
Last, we will calculate each author independent variable separated by discipline and then visualize those slopes for each variable.

In [0]:
# explode
df_hyp2 = df_hyp2.withColumn("ASJC", explode("ASJC"))
df_hyp2 = df_hyp2.withColumn("ASJC", df_hyp2.ASJC.cast(IntegerType()))

df_hyp2 = df_hyp2\
  .withColumn('subjareas',
              when(df_hyp2.ASJC.between(1100, 1199), "Life Sciences")\
  .when(df_hyp2.ASJC.between(1200, 1299), "Social Sciences")\
  .when(df_hyp2.ASJC.between(1300, 1399), "Life Sciences")\
  .when(df_hyp2.ASJC.between(1400, 1499), "Social Sciences")\
  .when(df_hyp2.ASJC.between(1500, 1799), "Physical Sciences")\
  .when(df_hyp2.ASJC.between(1800, 1899), "Social Sciences")\
  .when(df_hyp2.ASJC.between(1900, 1999), "Physical Sciences")\
  .when(df_hyp2.ASJC.between(2000, 2099), "Social Sciences")\
  .when(df_hyp2.ASJC.between(2100, 2399), "Physical Sciences")\
  .when(df_hyp2.ASJC.between(2400, 2499), "Life Sciences")\
  .when(df_hyp2.ASJC.between(2500, 2699), "Physical Sciences")\
  .when(df_hyp2.ASJC.between(2700, 2799), "Health Sciences")\
  .when(df_hyp2.ASJC.between(2800, 2899), "Life Sciences")\
  .when(df_hyp2.ASJC.between(2900, 2999), "Health Sciences")\
  .when(df_hyp2.ASJC.between(3000, 3099), "Life Sciences")\
  .when(df_hyp2.ASJC.between(3100, 3199), "Physical Sciences")\
  .when(df_hyp2.ASJC.between(3200, 3399), "Social Sciences")\
  .when(df_hyp2.ASJC.between(3400, 3699), "Health Sciences")\
  .otherwise("Multidisciplinary")
  )

In [0]:
for AREA in descriptives_output_df.subjareas.unique():
  if AREA == 'undefined': continue
  print(AREA)
  print("\n-------\n")

  # loop over all the variables
  for vars in independent_vars:
    # citations overall 
    # create dataframe, for these use unique Eids
    if (vars == "country_count") | (vars == "inst_count") | (vars == "gender_percent"):
      df_hyp2_overall = df_hyp2.dropDuplicates(['Eid'])
    elif (vars == "HIndex") | (vars == "HIndex_noself"):
      df_hyp2_overall = df_hyp2.filter((col("Authorseq") == 1))
    elif (vars == "IPG_index"):
      df_hyp2_overall = df_hyp2.filter((col("Authorseq") == 1))\
        .filter((col("Inferred_Probable_Gender") == "male") | (col("Inferred_Probable_Gender") == "female"))
    elif (vars == "2HIndex") | (vars == "2HIndex_noself"):
      df_hyp2_overall = df_hyp2.filter((col("Authorseq") == col("team_size")))
      vars = vars[1:]
    elif (vars == "2IPG_index"):
      df_hyp2_overall = df_hyp2.filter((col("Authorseq") == col("team_size")))\
        .filter((col("Inferred_Probable_Gender") == "male") | (col("Inferred_Probable_Gender") == "female"))
      vars = vars[1:]    

    # also filter for subject area 
    df_hyp2_overall = df_hyp2_overall.filter(col("subjareas") == AREA)
    
    # should drop nulls in X
    vectorAssembler = VectorAssembler(inputCols = ['Year', 'team_size', vars], outputCol = "pub_year")
    df_hyp2_overall = vectorAssembler.setHandleInvalid("skip").transform(df_hyp2_overall)

    df_hyp2_overall.cache()

    print(vars)
    print("\n----------\n")

    # put in the features X and prediction Y
    lr = LinearRegression(featuresCol = 'pub_year', labelCol = 'CitationCount')
    lr_model = lr.fit(df_hyp2_overall)
    model_output_df = modelsummary(lr_model, ("hyp2_CitationCount_"+vars+"_"+AREA), model_output_df)

    ## citations_5y
    # same DF just drop NULL citations_5y and newer articles 
    # if no citationcount then don't trust citations_5y
    df_hyp2_overall = df_hyp2_overall.where(col("Citations_5y").isNotNull())\
      .filter(col("Year") < 2017)

    # put in the features X and prediction Y
    lr = LinearRegression(featuresCol = 'pub_year', labelCol = 'Citations_5y')
    lr_model = lr.fit(df_hyp2_overall)
    model_output_df = modelsummary(lr_model, ("hyp2_Citation5y_"+vars+"_"+AREA), model_output_df)
    df_hyp2_overall.unpersist()

# Output Tables

Output tables for writing manuscript in R markdown.

In [0]:
# write out results section until I can get download link
pd.set_option('display.max_rows', None)
model_output_df

,model,coef,se,t,p,r2
0,hyp2_CitationCount_country_count,-0.465274,0.002255,-206.294193,0.0,0.00676
1,hyp2_CitationCount_country_count,-0.022046,0.001588,-13.878923,0.0,0.00676
2,hyp2_CitationCount_country_count,7.458726,0.04044,184.438618,0.0,0.00676
3,hyp2_CitationCount_country_count,949.380812,4.517021,210.17851,0.0,0.00676
4,hyp2_Citation5y_country_count,0.221818,0.00075,295.861074,0.0,0.031311
5,hyp2_Citation5y_country_count,0.009434,0.000571,16.519718,0.0,0.031311
6,hyp2_Citation5y_country_count,4.461241,0.014662,304.280577,0.0,0.031311
7,hyp2_Citation5y_country_count,-440.198178,1.497479,-293.959494,0.0,0.031311
8,hyp2_CitationCount_inst_count,-0.492492,0.002281,-215.950153,0.0,0.006752
9,hyp2_CitationCount_inst_count,-0.156769,0.002031,-77.182576,0.0,0.006752
10,hyp2_CitationCount_inst_count,2.757967,0.014971,184.223003,0.0,0.006752
11,hyp2_CitationCount_inst_count,1008.468323,4.569144,220.712749,0.0,0.006752
12,hyp2_Citation5y_inst_count,0.19721,0.000759,259.888503,0.0,0.034612
13,hyp2_Citation5y_inst_count,-0.108553,0.000767,-141.561274,0.0,0.034612
14,hyp2_Citation5y_inst_count,2.08084,0.006028,345.219511,0.0,0.034612
15,hyp2_Citation5y_inst_count,-388.81816,1.516042,-256.469265,0.0,0.034612
16,hyp2_CitationCount_gender_percent,-0.417073,0.0023,-181.297645,0.0,0.003604
17,hyp2_CitationCount_gender_percent,0.110898,0.001416,78.310549,0.0,0.003604
18,hyp2_CitationCount_gender_percent,-1.945399,0.112516,-17.289962,0.0,0.003604
19,hyp2_CitationCount_gender_percent,862.903342,4.629993,186.372485,0.0,0.003604
20,hyp2_Citation5y_gender_percent,0.243836,0.000759,321.087257,0.0,0.020197
21,hyp2_Citation5y_gender_percent,0.089239,0.000508,175.820333,0.0,0.020197
22,hyp2_Citation5y_gender_percent,-2.236538,0.033723,-66.321758,0.0,0.020197
23,hyp2_Citation5y_gender_percent,-477.646237,1.522988,-313.624518,0.0,0.020197
24,hyp2_CitationCount_HIndex,-0.118855,0.002468,-48.153781,0.0,0.029879
25,hyp2_CitationCount_HIndex,0.067646,0.001742,38.832669,0.0,0.029879
26,hyp2_CitationCount_HIndex,0.951383,0.001849,514.666358,0.0,0.029879
27,hyp2_CitationCount_HIndex,248.806216,4.95911,50.171545,0.0,0.029879
28,hyp2_Citation5y_HIndex,0.31183,0.000797,391.056459,0.0,0.048732
29,hyp2_Citation5y_HIndex,0.088644,0.000633,140.070966,0.0,0.048732
30,hyp2_Citation5y_HIndex,0.239571,0.000506,473.685085,0.0,0.048732
31,hyp2_Citation5y_HIndex,-619.453921,1.596838,-387.925242,0.0,0.048732
32,hyp2_CitationCount_HIndex_noself,-0.085779,0.002484,-34.536922,0.0,0.031889
33,hyp2_CitationCount_HIndex_noself,0.0746,0.001742,42.818681,0.0,0.031889
34,hyp2_CitationCount_HIndex_noself,1.094688,0.002048,534.430274,0.0,0.031889
35,hyp2_CitationCount_HIndex_noself,181.933891,4.990353,36.457115,0.0,0.031889
36,hyp2_Citation5y_HIndex_noself,0.318835,0.000799,398.811051,0.0,0.050449
37,hyp2_Citation5y_HIndex_noself,0.090972,0.000632,143.868587,0.0,0.050449
38,hyp2_Citation5y_HIndex_noself,0.271586,0.000558,486.79351,0.0,0.050449
39,hyp2_Citation5y_HIndex_noself,-633.577784,1.601068,-395.722085,0.0,0.050449
40,hyp2_CitationCount_IPG_index,-0.437465,0.002808,-155.816246,0.0,0.003717
41,hyp2_CitationCount_IPG_index,0.158903,0.002109,75.358458,0.0,0.003717
42,hyp2_CitationCount_IPG_index,1.943423,0.046601,41.703786,0.0,0.003717
43,hyp2_CitationCount_IPG_index,902.018599,5.625434,160.346504,0.0,0.003717
44,hyp2_Citation5y_IPG_index,0.234508,0.000905,259.022628,0.0,0.018942
45,hyp2_Citation5y_IPG_index,0.099453,0.000656,151.515699,0.0,0.018942
46,hyp2_Citation5y_IPG_index,1.000886,0.014347,69.764006,0.0,0.018942
47,hyp2_Citation5y_IPG_index,-460.772656,1.809785,-254.600752,0.0,0.018942
48,hyp2_CitationCount_HIndex,-0.428087,0.002375,-180.244005,0.0,0.033085
49,hyp2_CitationCount_HIndex,0.058917,0.001515,38.890754,0.0,0.033085
50,hyp2_CitationCount_HIndex,0.671773,0.001233,544.857226,0.0,0.033085
51,hyp2_CitationCount_HIndex,866.230439,4.765696,181.76369,0.0,0.033085
52,hyp2_Citation5y_HIndex,0.226092,0.000788,286.957423,0.0,0.0708
53,hyp2_Citation5y_HIndex,0.068689,0.000535,128.387545,0.0,0.0708
54,hyp2_Citation5y_HIndex,0.22622,0.000356,635.39603,0.0,0.0708
55,hyp2_Citation5y_HIndex,-449.888346,1.575871,-285.485603,0.0,0.0708
56,hyp2_CitationCount_HIndex_noself,-0.411716,0.002381,-172.911512,0.0,0.034622
57,hyp2_CitationCount_HIndex_noself,0.064399,0.001515,42.505605,0.0,0.034622
58,hyp2_CitationCount_HIndex_noself,0.753263,0.001347,559.055669,0.0,0.034622
59,hyp2_CitationCount_HIndex_noself,833.154735,4.77811,174.369098,0.0,0.034622
60,hyp2_Citation5y_HIndex_noself,0.231804,0.000788,294.097179,0.0,0.072485
61,hyp2_Citation5y_HIndex_noself,0.071115,0.000535,133.000247,0.0,0.072485
62,hyp2_Citation5y_HIndex_noself,0.250192,0.000388,645.237399,0.0,0.072485
63,hyp2_Citation5y_HIndex_noself,-461.34127,1.576578,-292.621959,0.0,0.072485
64,hyp2_CitationCount_IPG_index,-0.427454,0.002708,-157.828953,0.0,0.003743
65,hyp2_CitationCount_IPG_index,0.119744,0.001737,68.937537,0.0,0.003743
66,hyp2_CitationCount_IPG_index,0.843494,0.053566,15.746859,0.0,0.003743
67,hyp2_CitationCount_IPG_index,882.757558,5.428821,162.605771,0.0,0.003743
68,hyp2_Citation5y_IPG_index,0.245036,0.000898,272.763383,0.0,0.018536
69,hyp2_Citation5y_IPG_index,0.090516,0.0006,150.982154,0.0,0.018536
70,hyp2_Citation5y_IPG_index,0.496223,0.017238,28.785755,0.0,0.018536
71,hyp2_Citation5y_IPG_index,-481.520205,1.796343,-268.055769,0.0,0.018536

In [0]:
descriptives_output_df

EXECUTION DETAILS:
Spark version: 12.2.x-aarch64-scala2.12,
Cluster Node Type: r6gd.2xlarge,
Driver Node Type: r6gd.2xlarge,
Worker Node Type: r6gd.2xlarge

DATA SNAPSHOT DETAILS:
This notebook uses the latest snapshot date for this version: "v008.20230509104116/", (09 May 2023)

 The following are the Scopus snapshot dates available for datasets at v008:
['v008.20220314092239/', 'v008.20220906063204/', 'v008.20221021151538/', 'v008.20230509104116/']
(If you want to use a different snapshot, in the first cell of your notebook, set the variable `custom_snapshot_date` to one of the options listed above (string data type))

DATA SAMPLE DETAILS:
Setting paths to run on full datasets (100% Scopus publication volume)

In [0]:
model_output_df.to_csv('/dbfs/Projects/proj_050_teamsci/model_output_200723_part2.csv')
descriptives_output_df.to_csv('/dbfs/Projects/proj_050_teamsci/descriptives_output_df_200723_part2.csv')

In [0]:
%fs ls s3a://elsevier-fcads-icsrlab-output/shared/proj_050_teamsci

path,name,size,modificationTime
s3a://elsevier-fcads-icsrlab-output/shared/proj_050_teamsci/descriptives_output_df_200723_part2.csv,descriptives_output_df_200723_part2.csv,53,1689933341000
s3a://elsevier-fcads-icsrlab-output/shared/proj_050_teamsci/model_output_200723_part2.csv,model_output_200723_part2.csv,8325,1689933305000